### PR TITLE
Kickstart refactor

### PR DESCRIPTION
**Pull request by abn**
Major refactor of kickstarts.

### CODE REVIEW

**Comment by abn** [comment]
Requesting 3 acks. @ckannan @dfj @paulgampe @juliettkilotango

**Comment by dfj** [comment]
Looks good to me. Nitpick: cloudrouter-base.ks could do with a few comments to explain why certain settings are used.

**Comment by paulgampe** [comment]
I don't think the sed scripts are required anymore. I believe I fixed that releasearch patch in the cloudrouter-release rpm now.

**Comment by abn** [comment]
@dfj @paulgampe review comments processed and changes implemented.

**Comment by dfj** [comment]
Merged.

**Pull request closed without merging**
